plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.volodapatik.rtsprelay'
    compileSdk 34

    defaultConfig {
        applicationId 'com.volodapatik.rtsprelay'
        minSdk 22
        targetSdk 28
        versionCode 1
        versionName '0.1.0'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
